/*
 * Yokudlela Table API
 * description = \"Yokudlela Table API for Graphical User Interface .
 *
 * OpenAPI spec version: v1
 * Contact: krisztian_karoczkai@4dsoft.hu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package hu.yokudlela.media.java.clients.invoker.auth;

public enum OAuthFlow {
    accessCode, implicit, password, application
}
