/*
 * Yokudlela Storage API
 * description =Yokudlela Waste Management API for Graphical User Interface .
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package hu.yokudlela.media.java.clients.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.time.OffsetDateTime;
/**
 * Waste
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-12-07T18:07:22.178523900+01:00[Europe/Prague]")
public class Waste {
  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("removed")
  private Boolean removed = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("arrivedAt")
  private java.time.LocalDateTime arrivedAt = null;

  @JsonProperty("price")
  private Double price = null;

  @JsonProperty("count")
  private Integer count = null;

  public Waste id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public Waste removed(Boolean removed) {
    this.removed = removed;
    return this;
  }

   /**
   * Get removed
   * @return removed
  **/
  @Schema(description = "")
  public Boolean isRemoved() {
    return removed;
  }

  public void setRemoved(Boolean removed) {
    this.removed = removed;
  }

  public Waste name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Waste arrivedAt(java.time.LocalDateTime arrivedAt) {
    this.arrivedAt = arrivedAt;
    return this;
  }

   /**
   * Get arrivedAt
   * @return arrivedAt
  **/
  @Schema(description = "")
  public java.time.LocalDateTime getArrivedAt() {
    return arrivedAt;
  }

  public void setArrivedAt(java.time.LocalDateTime arrivedAt) {
    this.arrivedAt = arrivedAt;
  }

  public Waste price(Double price) {
    this.price = price;
    return this;
  }

   /**
   * Get price
   * @return price
  **/
  @Schema(description = "")
  public Double getPrice() {
    return price;
  }

  public void setPrice(Double price) {
    this.price = price;
  }

  public Waste count(Integer count) {
    this.count = count;
    return this;
  }

   /**
   * Get count
   * @return count
  **/
  @Schema(description = "")
  public Integer getCount() {
    return count;
  }

  public void setCount(Integer count) {
    this.count = count;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Waste waste = (Waste) o;
    return Objects.equals(this.id, waste.id) &&
        Objects.equals(this.removed, waste.removed) &&
        Objects.equals(this.name, waste.name) &&
        Objects.equals(this.arrivedAt, waste.arrivedAt) &&
        Objects.equals(this.price, waste.price) &&
        Objects.equals(this.count, waste.count);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, removed, name, arrivedAt, price, count);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Waste {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    removed: ").append(toIndentedString(removed)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    arrivedAt: ").append(toIndentedString(arrivedAt)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
